from pathlib import Path
import json,hashlib,datetime
b=Path(__file__).resolve().parent;p=Path('<submission>')
def passage(path,a,z):
 s=(p/path).read_text();return {'source':path,'line_start':a,'line_end':z,'text':'\n'.join(s.splitlines()[a-1:z]),'source_sha256':hashlib.sha256((p/path).read_bytes()).hexdigest()}
x={'created_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'FROZEN BEFORE INSPECTING CURRENT GOAL IMPLEMENTATION; NO MODEL CALLS','independence_note':'New exact questions independently authored from the supplied assignment and raw sources. Evaluator knows earlier implementation/failures from its prior reviews; therefore these are held-out question wordings and expectations, not a claim of evaluator blindness to the project. Existing B cases remain unchanged.','cases':[
 {'id':'H1-domain-draft','mode':'chat','fresh_session':True,'message':'Write a two-sentence invitation to a casual study group on AI alignment. Invent no venue, date, or participant details.','expected':{'retrieval_called':False,'behavior':['Provide a usable invitation draft labelled as a suggestion','Do not invent concrete date, location, attendees or personal facts','No unrelated source citations or insufficient-evidence refusal'],'sentence_count_target':2}},
 {'id':'H2-capability-paraphrase','mode':'chat','fresh_session':True,'message':'Please list the commands you support and one thing you cannot do.','expected':{'retrieval_called':False,'behavior':['Accurately describe chat, ask, search, ingest and help (additional implemented commands are acceptable)','Name a real unsupported capability, such as web browsing or sending email','Do not overclaim file editing, web lookup, or autonomous personal memory','No insufficient-evidence refusal or source citations'] }},
 {'id':'H3-topic-transition','mode':'chat','fresh_session':True,'turns':[{'message':'What do my notes say about preferences versus interests?','expected':{'retrieval_called':True,'behavior':['Explain that a stated or observed preference may be shaped or manipulated against a person\'s interests','Cite an actual retrieved source'],'expected_passages':[passage('vault/raw/alignment-lecture-notes.md',23,25),passage('vault/raw/alignment-lecture-notes.md',33,37)]}},{'message':'For an unrelated community activity, suggest three names for a book club.','expected':{'retrieval_called':False,'behavior':['Offer three book-club names as suggestions','Do not keep answering the AI-safety question','No evidence citations or unsupported personal facts'],'note':'Carrying previous evidence internally is not itself a failure; the visible answer must respect the explicit new topic.'}}]},
 {'id':'H4-response-coverage','mode':'ask','question':'Which responses do the notes propose for economic displacement and for AI-generated content crowding out human content?','expected_claims':['Proactive job creation and reskilling, with coordination between education, companies and government','Universal Basic Income','A human-as-bottleneck approach in which AI abundance increases human leverage','Mandatory labeling of AI-generated content for the cultural-content problem'],'expected_passages':[passage('vault/raw/risk-defenses-notes.md',27,34)],'forbidden':['Calling the proposals measured successes or enacted policy','Replacing one requested problem with an unrelated governance discussion'],'coverage_rule':'All four responses must be present. Semantically supported partial answers receive PARTIAL, not PASS.'},
 {'id':'H5-missing-efficacy','mode':'ask','question':'What measured success rate do these notes report for detecting deceptive reasoning?','expected':['Explicitly state insufficient evidence for a measured success rate','Do not invent a percentage, accuracy benchmark or claim of validated detector effectiveness'],'expected_passages':[],'nearby_nonanswer_passage':passage('vault/raw/alignment-fundamentals-notes.md',47,49)}
]}
f=b/'heldout-expectations.json'
if f.exists():raise SystemExit('Refusing to overwrite frozen held-out expectations')
f.write_text(json.dumps(x,indent=2,ensure_ascii=False)+'\n')
(b/'heldout-expectations.sha256').write_text(hashlib.sha256(f.read_bytes()).hexdigest()+'  heldout-expectations.json\n')
print('Frozen',len(x['cases']),'new cases; H3 has two conversational turns.')
